spring:
  cloud:
    gateway:
      routes:
        - id: stagiaire-service
          uri: http://localhost:8081/
          predicates:
            - Path=/api/stagiaire/**
        - id: project-service
          uri: http://localhost:8082/
          predicates:
            - Path=/api/project/**
        - id: evaluation-service
            uri: http://localhost:8083/
            predicates:
              - Path=/api/evaluation/**
        - id: supervisor-service
            uri: http://localhost:8084/
            predicates:
              - Path=/api/supervisor/**
  application:
    name: gateway-service

server:
  port: 8888