server:
  port: 8888

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: stagiaire-service
          uri: lb://STAGIAIRE-SERVICE
          predicates:
            - Path=/api/stagiaire/**
        - id: project-service
          uri: lb://PROJECT-SERVICE
          predicates:
            - Path=/api/project/**
        - id: evaluation-service
          uri: lb://EVALUATION-SERVICE
          predicates:
            - Path=/api/evaluation/**
        - id: supervisor-service
          uri: lb://SUPERVISOR-SERVICE
          predicates:
            - Path=/api/supervisor/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.security: DEBUG
