spring:
  application:
    name: supervisor-service

server:
  port: 8084

spring.datasource:
  url: jdbc:mysql://localhost:3306/bd-supervisor-ms?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
  username: root
  password: 09132339Aa

spring.jpa:
  show-sql: true
  hibernate.ddl-auto: update

security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: http://localhost:8080/realms/Gestion-Stagiaire

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
